# Generated by Django 5.1.1 on 2024-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='bank_booking_ref_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='irctc_order_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='bank_booking_ref_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='bank_refund_ref_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
